rabbitmq:
  image: rabbitmq:3-management
  restart: always
  ports:
  - 5672:5672 # port for the daemon API, can be exposed to public.
  - 15672:15672 # port for the Management interface
  env_file:
    - .secret
